FROM python:3

WORKDIR /code
EXPOSE 5001


RUN apt-get -y update
RUN apt-get -y install openjdk-8-jdk
RUN update-alternatives --config java

COPY requirements.txt .
RUN pip install -r requirements.txt



COPY ./python-server/ .
RUN ["python", "serverless.py"]
CMD ["gunicorn","-b", "0.0.0.0:5001","-w", "2", "server:app"]
